[project]
name = "ai-skin-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=1.6.0",
    "elevenlabs>=2.68.0",
    "gradio>=5.0.0",
    "groq>=1.7.0",
    "openai>=3.14.1",
    "opencv-python>=5.0.0.93",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.3",
    "speechrecognition>=3.17.0",
    "xai-sdk>=1.19.0",
]
